"""Generate unexecuted Colab notebook for the 100K pilot pipeline with checked execution and audit gates."""
import json
from pathlib import Path


def generate_colab_notebook():
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Deepfake Detection: Selectable Training Size (Google Colab)\n",
                    "\n",
                    "**Hardware**: Google Colab with NVIDIA L4 (24 GB) or 2x T4 (16 GB) GPU.\n",
                    "**Protocol**: 3-Stage fresh training on a selectable subset or all eligible training images from one shared folder, followed by controlled fusion comparisons, multi-seed validation, and targeted ablations.\n",
                    "\n",
                    "### Pipeline Execution Sequence:\n",
                    "1. **Environment Setup & Sizing**: Hardware detection, drive mount, dynamic batch/accumulation sizing, checked runner definition.\n",
                    "2. **Data Preparation & Audit Gate**: Auditable training-size selection with connected-component grouping, frame capping, and mandatory hash-verified integrity audit.\n",
                    "3. **Stage 1**: Standalone RGB Expert (`Wang2020_128`).\n",
                    "4. **Stage 2**: Standalone Wavelet Expert (`WolterWavelet2021_128`, Haar level 3, `signed_log1p`).\n",
                    "5. **Stage 3**: Controlled Fusion Heads on Frozen Experts (`Fusion_128` Gated, `Fusion_128` Concat, `MHA_128` Token Attention).\n",
                    "6. **Multi-Seed & Analysis**: 3 independent training runs with dev Youden J threshold calibration and paired comparisons.\n",
                    "7. **Optional Post-Training**: Explicit opt-in pixel-space robustness (JPEG, blur, noise, FGSM, PGD) & latency/memory/FLOPs profiling.\n",
                    "\n",
                    "> **Note**: All cells are unexecuted and enforce fail-closed checked execution. Failures in preparation or audit immediately block training."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 1. Mount Google Drive and Configure Working Directories\n",
                    "import os\n",
                    "from pathlib import Path\n",
                    "\n",
                    "# NOTE ON STORAGE PERSISTENCE:\n",
                    "# /content is ephemeral scratch storage wiped when the Colab runtime disconnects.\n",
                    "# For persistent checkpoints and experiment results, mount Google Drive:\n",
                    "# from google.colab import drive\n",
                    "# drive.mount('/content/drive')\n",
                    "# OUTPUT_BASE = Path('/content/drive/MyDrive/deepfake_experiments').resolve()\n",
                    "\n",
                    "REPO_ROOT = Path('/content/Novel-Deepfake-Detection').resolve()\n",
                    "DATA_ROOT = Path('/content/data').resolve()\n",
                    "# Change only TRAIN_SIZE to reuse the SAME DATA_ROOT and POOL_MANIFEST.\n",
                    "TRAIN_SIZE = 100_000  # 200_000, 400_000, or 'all'\n",
                    "FRAME_CAP = 15  # Subset policy; ignored for 'all' (no training frame cap).\n",
                    "ALLOW_SHORTFALL = False  # Set True only if you accept fewer than the requested count.\n",
                    "_size = str(TRAIN_SIZE).strip().lower()\n",
                    "if _size != 'all' and (not _size.isdecimal() or int(_size) <= 0 or int(_size) % 2):\n",
                    "    raise ValueError(\"TRAIN_SIZE must be a positive even count or 'all'\")\n",
                    "TRAIN_SIZE = _size\n",
                    "OUTPUT_BASE = Path('/content/experiments').resolve()  # Ephemeral unless set to Drive\n",
                    "from uuid import uuid4\n",
                    "OUTPUT_ROOT = OUTPUT_BASE / f'train_{TRAIN_SIZE}_{uuid4().hex[:10]}'\n",
                    "OUTPUT_ROOT.mkdir(parents=True, exist_ok=False)\n",
                    "\n",
                    "# Explicit Pool Manifest Configuration:\n",
                    "# Verified source manifest with required schema:\n",
                    "# sample_id, path, label, split, dataset_source, group_id, source_video_id\n",
                    "POOL_MANIFEST = DATA_ROOT / 'pool_manifest.csv'\n",
                    "# Reuse a saved verified selection for new models/seeds without preparing again.\n",
                    "PREPARED_MANIFEST = None  # Set Path('/path/to/saved/selected_manifest.csv') after preparation/recovery.\n",
                    "\n",
                    "print(f'Repository root:  {REPO_ROOT}')\n",
                    "print(f'Dataset root:     {DATA_ROOT}')\n",
                    "print(f'Outputs root:     {OUTPUT_ROOT}')\n",
                    "print(f'Pool manifest:    {POOL_MANIFEST}')\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 2. Hardware Detection, Sizing & Fail-Closed Checked Runner\n",
                    "import subprocess\n",
                    "import sys\n",
                    "import torch\n",
                    "\n",
                    "gpu_count = torch.cuda.device_count()\n",
                    "gpu_name = torch.cuda.get_device_name(0) if gpu_count > 0 else 'CPU'\n",
                    "vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3) if gpu_count > 0 else 0.0\n",
                    "\n",
                    "print(f'Detected {gpu_count} GPU(s): {gpu_name} ({vram_gb:.1f} GB VRAM)')\n",
                    "\n",
                    "# Sizing policy:\n",
                    "# L4 (24GB): Batch size 32 with 2 accum steps -> Effective batch 64\n",
                    "# T4 (16GB): Batch size 16 with 4 accum steps -> Effective batch 64\n",
                    "# 2x T4 (DDP): Batch size 16 per GPU with 2 accum steps -> Effective batch 64\n",
                    "if 'L4' in gpu_name:\n",
                    "    BATCH_SIZE = 32\n",
                    "    GRAD_ACCUM = 2\n",
                    "    USE_AMP = True\n",
                    "elif 'T4' in gpu_name:\n",
                    "    BATCH_SIZE = 16\n",
                    "    GRAD_ACCUM = 4 if gpu_count == 1 else 2\n",
                    "    USE_AMP = True\n",
                    "else:\n",
                    "    BATCH_SIZE = 16\n",
                    "    GRAD_ACCUM = 2\n",
                    "    USE_AMP = torch.cuda.is_available()\n",
                    "\n",
                    "EFFECTIVE_BATCH = BATCH_SIZE * GRAD_ACCUM * max(1, gpu_count)\n",
                    "AMP_FLAG = \"--use_amp\" if USE_AMP else \"\"\n",
                    "LAUNCH_CMD = f\"torchrun --nproc_per_node={gpu_count}\" if gpu_count > 1 else \"python\"\n",
                    "print(f'Configured: Micro-batch={BATCH_SIZE}, Accum={GRAD_ACCUM}, Effective Batch={EFFECTIVE_BATCH}, AMP={USE_AMP}')\n",
                    "print(f'Launch command: {LAUNCH_CMD}')\n",
                    "\n",
                    "def run_checked(cmd, cwd=str(REPO_ROOT)):\n",
                    "    \"\"\"Execute argument list with check=True, proper cwd, and fail-closed error propagation.\"\"\"\n",
                    "    if isinstance(cmd, str):\n",
                    "        cmd = cmd.split()\n",
                    "    print(f'\\n[RUNNING]: {\" \".join(str(c) for c in cmd)}')\n",
                    "    return subprocess.run([str(c) for c in cmd], cwd=cwd, check=True)\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 3. Environment Dependencies Installation\n",
                    "!pip install -q timm pytorch-wavelets scikit-learn matplotlib seaborn\n",
                    "%cd {REPO_ROOT}\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 4. Select training rows from the shared image folder & audit\n",
                    "MANIFEST_PATH = Path(PREPARED_MANIFEST).resolve() if PREPARED_MANIFEST is not None else OUTPUT_ROOT / f'train_{TRAIN_SIZE}_manifest.csv'\n",
                    "AUDIT_REPORT = OUTPUT_ROOT / 'audit_report.json'\n",
                    "\n",
                    "if PREPARED_MANIFEST is not None:\n",
                    "    from data.manifest import verify_manifest_gate\n",
                    "    gate_info = verify_manifest_gate(MANIFEST_PATH, enforce_class_coverage=True, require_hashes=True)\n",
                    "    print(f'Reusing prepared selection: {MANIFEST_PATH} ({gate_info[\"samples\"]:,} total rows)')\n",
                    "    print('TRAIN_SIZE selection settings are ignored during reuse; dataset files must be unchanged.')\n",
                    "else:\n",
                    "    # Step 4a: Validate existence of verified pool manifest\n",
                    "    if not POOL_MANIFEST.is_file():\n",
                    "        raise FileNotFoundError(\n",
                    "            f'Verified pool manifest not found at: {POOL_MANIFEST}\\n'\n",
                    "            'Data preparation requires an auditable verified pool manifest CSV.\\n'\n",
                    "            'To create it:\\n'\n",
                    "            '1. Inventory raw sources: python prepare_dataset.py inventory --root <dir> --source <src> --output <src.csv>\\n'\n",
                    "            '2. Enrich with verified metadata (group_id, source_video_id, generator)\\n'\n",
                    "            '3. Combine and place at POOL_MANIFEST with required columns:\\n'\n",
                    "            '   sample_id, path, label, split, dataset_source, group_id, source_video_id'\n",
                    "        )\n",
                    "\n",
                    "    # Step 4b: Select only manifest rows; no images are copied or moved.\n",
                    "    prepare_cmd = [\n",
                    "        sys.executable, 'prepare_dataset.py', 'pilot',\n",
                    "        '--manifest', str(POOL_MANIFEST),\n",
                    "        '--root', str(DATA_ROOT),\n",
                    "        '--output', str(MANIFEST_PATH),\n",
                    "        '--train_size', str(TRAIN_SIZE),\n",
                    "        '--dev_ratio', '0.1',\n",
                    "        '--test_ratio', '0.1',\n",
                    "        '--frame_cap', str(FRAME_CAP),\n",
                    "        '--require_groups',\n",
                    "        '--seed', '42',\n",
                    "    ]\n",
                    "    if ALLOW_SHORTFALL:\n",
                    "        prepare_cmd.append('--allow_shortfall')\n",
                    "    run_checked(prepare_cmd)\n",
                    "    import json\n",
                    "    selection_report = json.loads(MANIFEST_PATH.with_suffix('.report.json').read_text())\n",
                    "    print(json.dumps(selection_report['training_selection'], indent=2))\n",
                    "    print(json.dumps(selection_report['shortage_summary'], indent=2))\n",
                    "\n",
                    "    # Step 4c: Audit split integrity, component separation, and write verification gate\n",
                    "    run_checked([\n",
                    "        sys.executable, 'prepare_dataset.py', 'audit',\n",
                    "        '--manifest', str(MANIFEST_PATH),\n",
                    "        '--output', str(AUDIT_REPORT),\n",
                    "        '--hash_cache', str(OUTPUT_BASE / 'hashes.sqlite'),\n",
                    "        '--hashes',\n",
                    "    ])\n",
                    "\n",
                    "    # Step 4d: Verify preparation success gate before continuing\n",
                    "    from data.manifest import verify_manifest_gate\n",
                    "    gate_info = verify_manifest_gate(MANIFEST_PATH, enforce_class_coverage=True, require_hashes=True)\n",
                    "    print(f'\\n[SUCCESS] Preparation audit gate verified:')\n",
                    "    print(f\"  Samples: {gate_info['samples']}, SHA256: {gate_info['manifest_sha256']}\")\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 5. Stage 1: Train Standalone RGB Expert (Wang2020_128)\n",
                    "from data.manifest import verify_manifest_gate\n",
                    "verify_manifest_gate(MANIFEST_PATH)\n",
                    "\n",
                    "s1_launch = LAUNCH_CMD.split()\n",
                    "s1_cmd = s1_launch + [\n",
                    "    'train.py',\n",
                    "    '--arch', 'Wang2020_128',\n",
                    "    '--dataroot', str(DATA_ROOT),\n",
                    "    '--manifest', str(MANIFEST_PATH),\n",
                    "    '--manifest_split', 'train',\n",
                    "    '--val_manifest', str(MANIFEST_PATH),\n",
                    "    '--val_manifest_split', 'dev',\n",
                    "    '--name', 'stage1_rgb_expert',\n",
                    "    '--run_id', 'seed42',\n",
                    "    '--checkpoints_dir', str(OUTPUT_ROOT / 'stage1_rgb'),\n",
                    "    '--batch_size', str(BATCH_SIZE),\n",
                    "    '--grad_accum_steps', str(GRAD_ACCUM),\n",
                    "    '--epochs', '10',\n",
                    "    '--lr', '0.0001',\n",
                    "    '--monitor_metric', 'auc',\n",
                    "    '--seed', '42',\n",
                    "]\n",
                    "if USE_AMP:\n",
                    "    s1_cmd.append('--use_amp')\n",
                    "run_checked(s1_cmd)\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 6. Stage 2: Train Standalone Wavelet Expert (WolterWavelet2021_128)\n",
                    "from data.manifest import verify_manifest_gate\n",
                    "verify_manifest_gate(MANIFEST_PATH)\n",
                    "\n",
                    "s2_launch = LAUNCH_CMD.split()\n",
                    "s2_cmd = s2_launch + [\n",
                    "    'train.py',\n",
                    "    '--arch', 'WolterWavelet2021_128',\n",
                    "    '--dataroot', str(DATA_ROOT),\n",
                    "    '--manifest', str(MANIFEST_PATH),\n",
                    "    '--manifest_split', 'train',\n",
                    "    '--val_manifest', str(MANIFEST_PATH),\n",
                    "    '--val_manifest_split', 'dev',\n",
                    "    '--name', 'stage2_wavelet_expert',\n",
                    "    '--run_id', 'seed42',\n",
                    "    '--checkpoints_dir', str(OUTPUT_ROOT / 'stage2_wavelet'),\n",
                    "    '--wavelet_type', 'haar',\n",
                    "    '--wavelet_level', '3',\n",
                    "    '--wavelet_log_mode', 'signed_log1p',\n",
                    "    '--batch_size', str(BATCH_SIZE),\n",
                    "    '--grad_accum_steps', str(GRAD_ACCUM),\n",
                    "    '--epochs', '10',\n",
                    "    '--lr', '0.0001',\n",
                    "    '--monitor_metric', 'auc',\n",
                    "    '--seed', '42',\n",
                    "]\n",
                    "if USE_AMP:\n",
                    "    s2_cmd.append('--use_amp')\n",
                    "run_checked(s2_cmd)\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 7. Stage 3: Train Fusion Heads on Frozen Experts\n",
                    "from data.manifest import verify_manifest_gate\n",
                    "verify_manifest_gate(MANIFEST_PATH)\n",
                    "\n",
                    "RGB_CKPT = OUTPUT_ROOT / 'stage1_rgb' / 'stage1_rgb_expert_seed42' / 'checkpoints' / 'best.pth'\n",
                    "WAV_CKPT = OUTPUT_ROOT / 'stage2_wavelet' / 'stage2_wavelet_expert_seed42' / 'checkpoints' / 'best.pth'\n",
                    "s3_launch = LAUNCH_CMD.split()\n",
                    "\n",
                    "# 7a. Corrected Multi-Key Token Attention\n",
                    "s3_token_cmd = s3_launch + [\n",
                    "    'train.py',\n",
                    "    '--arch', 'MHA_128',\n",
                    "    '--fusion_type', 'token_attention',\n",
                    "    '--rgb_model_path', str(RGB_CKPT),\n",
                    "    '--wavelet_model_path', str(WAV_CKPT),\n",
                    "    '--dataroot', str(DATA_ROOT),\n",
                    "    '--manifest', str(MANIFEST_PATH),\n",
                    "    '--manifest_split', 'train',\n",
                    "    '--val_manifest', str(MANIFEST_PATH),\n",
                    "    '--val_manifest_split', 'dev',\n",
                    "    '--name', 'stage3_token_attention',\n",
                    "    '--run_id', 'seed42',\n",
                    "    '--checkpoints_dir', str(OUTPUT_ROOT / 'stage3_token_attention'),\n",
                    "    '--batch_size', str(BATCH_SIZE),\n",
                    "    '--grad_accum_steps', str(GRAD_ACCUM),\n",
                    "    '--epochs', '10',\n",
                    "    '--monitor_metric', 'auc',\n",
                    "    '--seed', '42',\n",
                    "]\n",
                    "if USE_AMP:\n",
                    "    s3_token_cmd.append('--use_amp')\n",
                    "run_checked(s3_token_cmd)\n",
                    "\n",
                    "# 7b. Gated Fusion Control\n",
                    "s3_gated_cmd = s3_launch + [\n",
                    "    'train.py',\n",
                    "    '--arch', 'Fusion_128',\n",
                    "    '--fusion_type', 'gated',\n",
                    "    '--rgb_model_path', str(RGB_CKPT),\n",
                    "    '--wavelet_model_path', str(WAV_CKPT),\n",
                    "    '--dataroot', str(DATA_ROOT),\n",
                    "    '--manifest', str(MANIFEST_PATH),\n",
                    "    '--manifest_split', 'train',\n",
                    "    '--val_manifest', str(MANIFEST_PATH),\n",
                    "    '--val_manifest_split', 'dev',\n",
                    "    '--name', 'stage3_gated',\n",
                    "    '--run_id', 'seed42',\n",
                    "    '--checkpoints_dir', str(OUTPUT_ROOT / 'stage3_gated'),\n",
                    "    '--batch_size', str(BATCH_SIZE),\n",
                    "    '--grad_accum_steps', str(GRAD_ACCUM),\n",
                    "    '--epochs', '10',\n",
                    "    '--monitor_metric', 'auc',\n",
                    "    '--seed', '42',\n",
                    "]\n",
                    "if USE_AMP:\n",
                    "    s3_gated_cmd.append('--use_amp')\n",
                    "run_checked(s3_gated_cmd)\n",
                    "\n",
                    "# 7c. Concatenation MLP Control\n",
                    "s3_concat_cmd = s3_launch + [\n",
                    "    'train.py',\n",
                    "    '--arch', 'Fusion_128',\n",
                    "    '--fusion_type', 'concat',\n",
                    "    '--rgb_model_path', str(RGB_CKPT),\n",
                    "    '--wavelet_model_path', str(WAV_CKPT),\n",
                    "    '--dataroot', str(DATA_ROOT),\n",
                    "    '--manifest', str(MANIFEST_PATH),\n",
                    "    '--manifest_split', 'train',\n",
                    "    '--val_manifest', str(MANIFEST_PATH),\n",
                    "    '--val_manifest_split', 'dev',\n",
                    "    '--name', 'stage3_concat',\n",
                    "    '--run_id', 'seed42',\n",
                    "    '--checkpoints_dir', str(OUTPUT_ROOT / 'stage3_concat'),\n",
                    "    '--batch_size', str(BATCH_SIZE),\n",
                    "    '--grad_accum_steps', str(GRAD_ACCUM),\n",
                    "    '--epochs', '10',\n",
                    "    '--monitor_metric', 'auc',\n",
                    "    '--seed', '42',\n",
                    "]\n",
                    "if USE_AMP:\n",
                    "    s3_concat_cmd.append('--use_amp')\n",
                    "run_checked(s3_concat_cmd)\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 8. Development Threshold Calibration and Paired Model Comparison\n",
                    "TOKEN_PREDS = OUTPUT_ROOT / 'stage3_token_attention' / 'stage3_token_attention_seed42' / 'checkpoints' / 'dev_predictions.csv'\n",
                    "GATED_PREDS = OUTPUT_ROOT / 'stage3_gated' / 'stage3_gated_seed42' / 'checkpoints' / 'dev_predictions.csv'\n",
                    "\n",
                    "# Calibrate thresholds exclusively on development split predictions\n",
                    "run_checked([\n",
                    "    sys.executable, 'analyze_predictions.py', 'calibrate',\n",
                    "    '--predictions', str(TOKEN_PREDS),\n",
                    "    '--output', str(OUTPUT_ROOT / 'stage3_token_attention' / 'threshold_calibrated.json'),\n",
                    "])\n",
                    "\n",
                    "run_checked([\n",
                    "    sys.executable, 'analyze_predictions.py', 'calibrate',\n",
                    "    '--predictions', str(GATED_PREDS),\n",
                    "    '--output', str(OUTPUT_ROOT / 'stage3_gated' / 'threshold_calibrated.json'),\n",
                    "])\n",
                    "\n",
                    "# Paired comparison using independently calibrated development thresholds\n",
                    "run_checked([\n",
                    "    sys.executable, 'analyze_predictions.py', 'compare',\n",
                    "    '--predictions', str(TOKEN_PREDS), str(GATED_PREDS),\n",
                    "    '--threshold_file', str(OUTPUT_ROOT / 'stage3_token_attention' / 'threshold_calibrated.json'),\n",
                    "    '--threshold_file_other', str(OUTPUT_ROOT / 'stage3_gated' / 'threshold_calibrated.json'),\n",
                    "    '--bootstrap', '1000',\n",
                    "    '--output', str(OUTPUT_ROOT / 'paired_token_vs_gated.json'),\n",
                    "])\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 9. Multi-Seed Pipeline (Seeds 42, 43, 44)\n",
                    "# Repeat complete pipeline across 3 independent training seeds\n",
                    "# When all 3 runs complete, summarize seed variability:\n",
                    "# run_checked([\n",
                    "#     sys.executable, 'analyze_predictions.py', 'seeds',\n",
                    "#     '--predictions',\n",
                    "#         str(OUTPUT_ROOT / 'stage3_token_attention/stage3_token_attention_seed42/checkpoints/dev_predictions.csv'),\n",
                    "#         str(OUTPUT_ROOT / 'stage3_token_attention/stage3_token_attention_seed43/checkpoints/dev_predictions.csv'),\n",
                    "#         str(OUTPUT_ROOT / 'stage3_token_attention/stage3_token_attention_seed44/checkpoints/dev_predictions.csv'),\n",
                    "#     '--threshold_files',\n",
                    "#         str(OUTPUT_ROOT / 'stage3_token_attention/threshold_seed42.json'),\n",
                    "#         str(OUTPUT_ROOT / 'stage3_token_attention/threshold_seed43.json'),\n",
                    "#         str(OUTPUT_ROOT / 'stage3_token_attention/threshold_seed44.json'),\n",
                    "#     '--run_ids', 'seed42', 'seed43', 'seed44',\n",
                    "#     '--output', str(OUTPUT_ROOT / 'three_seed_variability.json'),\n",
                    "# ])\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 10. Optional Post-Training: Raw-Pixel Robustness and Attacks\n",
                    "# Explicit opt-in toggle to prevent accidental execution during Run All\n",
                    "RUN_OPTIONAL_ROBUSTNESS = False\n",
                    "\n",
                    "if RUN_OPTIONAL_ROBUSTNESS:\n",
                    "    ckpt = OUTPUT_ROOT / 'stage3_token_attention' / 'stage3_token_attention_seed42' / 'checkpoints' / 'best.pth'\n",
                    "    if ckpt.is_file():\n",
                    "        print(f'Evaluating robustness on {ckpt}...')\n",
                    "        run_checked([\n",
                    "            sys.executable, '-m', 'evaluation.robustness_cli',\n",
                    "            '--checkpoint', str(ckpt),\n",
                    "            '--val_root', str(DATA_ROOT),\n",
                    "            '--manifest', str(MANIFEST_PATH),\n",
                    "            '--split', 'dev',\n",
                    "            '--conditions', 'clean', 'jpeg_75', 'jpeg_30', 'blur_1', 'noise_3', 'fgsm', 'pgd',\n",
                    "            '--eps', '0.01568',\n",
                    "            '--output_dir', str(OUTPUT_ROOT / 'robustness_evaluation'),\n",
                    "        ])\n",
                    "    else:\n",
                    "        print(f'Checkpoint not found at {ckpt}. Complete Stage 3 training first.')\n",
                    "else:\n",
                    "    print('Optional robustness evaluation skipped (set RUN_OPTIONAL_ROBUSTNESS = True to run).')\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 11. Optional Post-Training: Latency, Peak Memory & FLOPs Profiling\n",
                    "# Explicit opt-in toggle to prevent accidental execution during Run All\n",
                    "RUN_OPTIONAL_PROFILING = False\n",
                    "\n",
                    "if RUN_OPTIONAL_PROFILING:\n",
                    "    ckpt = OUTPUT_ROOT / 'stage3_token_attention' / 'stage3_token_attention_seed42' / 'checkpoints' / 'best.pth'\n",
                    "    if ckpt.is_file():\n",
                    "        from evaluation.checkpoint_loader import CheckpointLoader\n",
                    "        from evaluation.end_to_end_profile import profile_pipeline\n",
                    "        import json\n",
                    "        loader = CheckpointLoader(str(ckpt))\n",
                    "        model = loader.load()\n",
                    "        results = profile_pipeline(model, batch_size=1, warmup=3, repeats=10)\n",
                    "        print(json.dumps(results, indent=2))\n",
                    "    else:\n",
                    "        print(f'Checkpoint not found at {ckpt}. Complete Stage 3 training first.')\n",
                    "else:\n",
                    "    print('Optional profiling skipped (set RUN_OPTIONAL_PROFILING = True to run).')\n"
                ]
            }
        ],
        "metadata": {
            "accelerator": "GPU",
            "colab": {"provenance": []},
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.12"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    out_path = Path("colab_pilot_pipeline.ipynb")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    print(f"Generated {out_path} ({len(notebook['cells'])} cells)")


if __name__ == "__main__":
    generate_colab_notebook()
